### ISSUE TITLE
issue # 3 index.jsx "[vite] Internal server error: Failed to resolve import "react-dom/client" from "src/index.jsx". Does the file exist?"

### ISSUE THREAD

**Issue by Artedys** [buildspace/buildspace-dao-final#18]
Hello,

The new index.jsx file as in the tutorial give this error "[vite] Internal server error: Failed to resolve import "react-dom/client" from "src/index.jsx". Does the file exist?"

The complete error is: "10:29:09 AM [vite] Internal server error: Failed to resolve import "react-dom/client" from "src/index.jsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/runner/12111028buildspace-dao-starter-v3/src/index.jsx
  1  |  var _jsxFileName = "/home/runner/12111028buildspace-dao-starter-v3/src/index.jsx";
  2  |  import React from "react";
  3  |  import { createRoot } from "react-dom/client";
     |                              ^
  4  |  import "./index.css";
  5  |  import App from "./App";
      at formatError (file:///home/runner/12111028buildspace-dao-starter-v3/node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:35044:46)
      at TransformContext.error (file:///home/runner/12111028buildspace-dao-starter-v3/node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:35040:19)
      at normalizeUrl (file:///home/runner/12111028buildspace-dao-starter-v3/node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:40248:33)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (file:///home/runner/12111028buildspace-dao-starter-v3/node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:40382:47)
      at async Object.transform (file:///home/runner/12111028buildspace-dao-starter-v3/node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:35293:30)
      at async loadAndTransform (file:///home/runner/12111028buildspace-dao-starter-v3/node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:39879:29)
"
<img width="653" alt="Capture d’écran 2022-11-12 à 11 37 22" src="https://user-images.githubusercontent.com/8425280/201470298-dcabbd95-822b-44b9-aa64-159890ca3a6c.png">

**Comment by Artedys** [comment]
By opposite in Terminal index.jx seems to run well 
![Uploading Capture d’écran 2022-11-12 à 12.23.27.png…]()

In Terminal the same code is OK
<img width="1785" alt="Capture d’écran 2022-11-12 à 12 26 41" src="https://user-images.githubusercontent.com/8425280/201471838-0cd7fc28-ee1f-407d-9def-8add34addf68.png">

**Comment by Artedys** [comment]
I close because it works in TERMINAL / but with a warning about Replit
